/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author oscar.domalo
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());

    /**
     * Creates new form PantallaPrincipal
     */
    
    Hilo h1, h2, h3;
    int tiempoSleep = 500;
    
    public PantallaPrincipal() {
        initComponents();
        jSliderHilo1.setValue(5);
        jSliderHilo2.setValue(5);
        jSliderHilo3.setValue(5);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonComenzarCarrera = new javax.swing.JButton();
        jSliderHilo1 = new javax.swing.JSlider();
        jLabelNombreHilo1 = new javax.swing.JLabel();
        jLabelPrioridad1 = new javax.swing.JLabel();
        jProgressBarHilo1 = new javax.swing.JProgressBar();
        jSliderHilo2 = new javax.swing.JSlider();
        jLabelNombreHilo2 = new javax.swing.JLabel();
        jLabelPrioridad2 = new javax.swing.JLabel();
        jProgressBarHilo2 = new javax.swing.JProgressBar();
        jProgressBarHilo3 = new javax.swing.JProgressBar();
        jSliderHilo3 = new javax.swing.JSlider();
        jLabelNombreHilo3 = new javax.swing.JLabel();
        jLabelPrioridad3 = new javax.swing.JLabel();
        jLabelContador1 = new javax.swing.JLabel();
        jLabelContador2 = new javax.swing.JLabel();
        jLabelContador3 = new javax.swing.JLabel();
        jLabelHiloGanador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonComenzarCarrera.setText("Comenzar carrera");
        jButtonComenzarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComenzarCarreraActionPerformed(evt);
            }
        });

        jSliderHilo1.setMaximum(10);
        jSliderHilo1.setMinimum(1);
        jSliderHilo1.setPaintLabels(true);
        jSliderHilo1.setPaintTicks(true);
        jSliderHilo1.setSnapToTicks(true);
        jSliderHilo1.setValue(5);
        jSliderHilo1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderHilo1StateChanged(evt);
            }
        });

        jLabelNombreHilo1.setText("Hilo 1");

        jLabelPrioridad1.setText("Prioridad: 5");

        jSliderHilo2.setMaximum(10);
        jSliderHilo2.setMinimum(1);
        jSliderHilo2.setPaintLabels(true);
        jSliderHilo2.setPaintTicks(true);
        jSliderHilo2.setSnapToTicks(true);
        jSliderHilo2.setValue(5);
        jSliderHilo2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderHilo2StateChanged(evt);
            }
        });

        jLabelNombreHilo2.setText("Hilo 2");

        jLabelPrioridad2.setText("Prioridad: 5");

        jSliderHilo3.setMaximum(10);
        jSliderHilo3.setMinimum(1);
        jSliderHilo3.setPaintLabels(true);
        jSliderHilo3.setPaintTicks(true);
        jSliderHilo3.setSnapToTicks(true);
        jSliderHilo3.setValue(5);
        jSliderHilo3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderHilo3StateChanged(evt);
            }
        });

        jLabelNombreHilo3.setText("Hilo 3");

        jLabelPrioridad3.setText("Prioridad: 5");

        jLabelContador1.setText("0");

        jLabelContador2.setText("0");

        jLabelContador3.setText("0");

        jLabelHiloGanador.setText("Hilo ganador:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNombreHilo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jProgressBarHilo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSliderHilo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrioridad1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNombreHilo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jProgressBarHilo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jSliderHilo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrioridad2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabelContador3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelNombreHilo3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jProgressBarHilo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jSliderHilo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabelHiloGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPrioridad3)))
                .addGap(67, 67, 67))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabelContador2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabelContador1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jButtonComenzarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButtonComenzarCarrera)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSliderHilo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreHilo1)
                    .addComponent(jLabelPrioridad1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarHilo1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelContador1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSliderHilo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreHilo2)
                    .addComponent(jLabelPrioridad2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarHilo2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelContador2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jLabelPrioridad3)
                        .addGap(143, 143, 143))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSliderHilo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombreHilo3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jProgressBarHilo3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelContador3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelHiloGanador)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonComenzarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComenzarCarreraActionPerformed
        // TODO add your handling code here:
        h1 = new Hilo("Hilo 1",jSliderHilo1,jLabelNombreHilo1,jProgressBarHilo1,jLabelContador1,
         jLabelPrioridad1,tiempoSleep,jButtonComenzarCarrera, jLabelHiloGanador);
        h2 = new Hilo("Hilo 2",jSliderHilo2,jLabelNombreHilo2,jProgressBarHilo2,jLabelContador2,
         jLabelPrioridad2,tiempoSleep,jButtonComenzarCarrera, jLabelHiloGanador);
        h3 = new Hilo("Hilo 3",jSliderHilo3,jLabelNombreHilo3,jProgressBarHilo3,jLabelContador3,
         jLabelPrioridad3,tiempoSleep,jButtonComenzarCarrera, jLabelHiloGanador);
        
        h1.setPriority(jSliderHilo1.getValue());
        h2.setPriority(jSliderHilo2.getValue());
        h3.setPriority(jSliderHilo3.getValue());
        Hilo.setStopHilo(false);
        
        h1.start();
        h2.start();
        h3.start();
        
        jButtonComenzarCarrera.setEnabled(false);
        jLabelHiloGanador.setText("");
        
        
        
        
    }//GEN-LAST:event_jButtonComenzarCarreraActionPerformed

    private void jSliderHilo1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderHilo1StateChanged
        // TODO add your handling code here:
        jLabelPrioridad1.setText("Prioridad: " + jSliderHilo1.getValue());
        
    }//GEN-LAST:event_jSliderHilo1StateChanged

    private void jSliderHilo2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderHilo2StateChanged
        // TODO add your handling code here:
        jLabelPrioridad2.setText("Prioridad: " + jSliderHilo2.getValue());

    }//GEN-LAST:event_jSliderHilo2StateChanged

    private void jSliderHilo3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderHilo3StateChanged
        // TODO add your handling code here:
        jLabelPrioridad3.setText("Prioridad: " + jSliderHilo3.getValue());

    }//GEN-LAST:event_jSliderHilo3StateChanged
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComenzarCarrera;
    private javax.swing.JLabel jLabelContador1;
    private javax.swing.JLabel jLabelContador2;
    private javax.swing.JLabel jLabelContador3;
    private javax.swing.JLabel jLabelHiloGanador;
    private javax.swing.JLabel jLabelNombreHilo1;
    private javax.swing.JLabel jLabelNombreHilo2;
    private javax.swing.JLabel jLabelNombreHilo3;
    private javax.swing.JLabel jLabelPrioridad1;
    private javax.swing.JLabel jLabelPrioridad2;
    private javax.swing.JLabel jLabelPrioridad3;
    private javax.swing.JProgressBar jProgressBarHilo1;
    private javax.swing.JProgressBar jProgressBarHilo2;
    private javax.swing.JProgressBar jProgressBarHilo3;
    private javax.swing.JSlider jSliderHilo1;
    private javax.swing.JSlider jSliderHilo2;
    private javax.swing.JSlider jSliderHilo3;
    // End of variables declaration//GEN-END:variables
}
