/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package contador;

/**
 *
 * @author oscar.domalo
 */
public class Principal extends javax.swing.JFrame {
    
    Contador h, h1;
    long valorContador, valorContador1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        h = new Contador(jLabelContador,0);
        h1 = new Contador(jLabelContador,0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtoniniciarContinuar = new javax.swing.JButton();
        jButtonParar = new javax.swing.JButton();
        jLabelContador = new javax.swing.JLabel();
        jButtoniniciarContinuar1 = new javax.swing.JButton();
        jButtonParar1 = new javax.swing.JButton();
        jLabelContador1 = new javax.swing.JLabel();
        jButtoniniciarContinuar2 = new javax.swing.JButton();
        jButtoniniciarContinuar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtoniniciarContinuar.setText("Iniciar");
        jButtoniniciarContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoniniciarContinuarActionPerformed(evt);
            }
        });

        jButtonParar.setText("Parar");
        jButtonParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPararActionPerformed(evt);
            }
        });

        jLabelContador.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelContador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelContador.setText("0");

        jButtoniniciarContinuar1.setText("Iniciar");
        jButtoniniciarContinuar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoniniciarContinuar1ActionPerformed(evt);
            }
        });

        jButtonParar1.setText("Parar");
        jButtonParar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParar1ActionPerformed(evt);
            }
        });

        jLabelContador1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabelContador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelContador1.setText("0");

        jButtoniniciarContinuar2.setText("Suspender");
        jButtoniniciarContinuar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoniniciarContinuar2ActionPerformed(evt);
            }
        });

        jButtoniniciarContinuar3.setText("Suspender");
        jButtoniniciarContinuar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoniniciarContinuar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelContador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonParar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtoniniciarContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtoniniciarContinuar2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtoniniciarContinuar3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabelContador1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonParar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtoniniciarContinuar1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtoniniciarContinuar1)
                    .addComponent(jButtoniniciarContinuar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtoniniciarContinuar2)
                    .addComponent(jButtoniniciarContinuar3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonParar1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelContador1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonParar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelContador, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtoniniciarContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoniniciarContinuarActionPerformed
        // TODO add your handling code here:
        if (jButtoniniciarContinuar.getText().equals("Iniciar")) {
            jButtoniniciarContinuar.setText("Continuar");
        }
        if (h.isAlive() && h != null) {}
        else{
               h = new Contador(jLabelContador,valorContador); 
               h.start();
        }
        
    }//GEN-LAST:event_jButtoniniciarContinuarActionPerformed

    private void jButtonPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPararActionPerformed
        // TODO add your handling code here:
        valorContador = h.getContador();
        h.pararHilo();
    }//GEN-LAST:event_jButtonPararActionPerformed

    private void jButtoniniciarContinuar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoniniciarContinuar1ActionPerformed
        // TODO add your handling code here:
        if (jButtoniniciarContinuar1.getText().equals("Iniciar")) {
            jButtoniniciarContinuar1.setText("Continuar");
        }
        if (h1.isAlive() && h != null) {}
        else{
               h1 = new Contador(jLabelContador1,valorContador1); 
               h1.start();
        }
    }//GEN-LAST:event_jButtoniniciarContinuar1ActionPerformed

    private void jButtonParar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParar1ActionPerformed
        // TODO add your handling code here:
        valorContador1 = h1.getContador();
        h1.pararHilo();
    }//GEN-LAST:event_jButtonParar1ActionPerformed

    private void jButtoniniciarContinuar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoniniciarContinuar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoniniciarContinuar2ActionPerformed

    private void jButtoniniciarContinuar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoniniciarContinuar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtoniniciarContinuar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonParar;
    private javax.swing.JButton jButtonParar1;
    private javax.swing.JButton jButtoniniciarContinuar;
    private javax.swing.JButton jButtoniniciarContinuar1;
    private javax.swing.JButton jButtoniniciarContinuar2;
    private javax.swing.JButton jButtoniniciarContinuar3;
    private javax.swing.JLabel jLabelContador;
    private javax.swing.JLabel jLabelContador1;
    // End of variables declaration//GEN-END:variables
}
