package metodowait;
/**
 *
 * @author oscar.domalo
 */
public class PantallaPrincipal extends javax.swing.JFrame {
 
    private static final java.util.logging.Logger logger = 
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());

    /**
     * Creates new form PantallaPrincipal
     */
    
     Hilo h1, h2;
       private boolean procesoIniciado = false;
    
    public PantallaPrincipal() {
        initComponents();
        // Deshabilitar botones inicialmente
        btnFinalizar.setEnabled(false);
        btnSuspender1.setEnabled(false);
        btnReanudar1.setEnabled(false);
        btnSuspender2.setEnabled(false);
        btnReanudar2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnComenzar = new javax.swing.JButton();
        lblEstado1 = new javax.swing.JLabel();
        lblEstado2 = new javax.swing.JLabel();
        btnSuspender1 = new javax.swing.JButton();
        btnSuspender2 = new javax.swing.JButton();
        btnReanudar1 = new javax.swing.JButton();
        btnReanudar2 = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        lblContador2 = new javax.swing.JLabel();
        lblContador1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EJECUTAR, SUSPENDER Y REANUDAR HILOS");

        btnComenzar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnComenzar.setText("Comenzar Proceso");
        btnComenzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComenzarActionPerformed(evt);
            }
        });

        lblEstado1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEstado1.setText("HILO 1");

        lblEstado2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEstado2.setText("HILO 2");

        btnSuspender1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSuspender1.setText("Suspender");
        btnSuspender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuspender1ActionPerformed(evt);
            }
        });

        btnSuspender2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSuspender2.setText("Suspender");
        btnSuspender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuspender2ActionPerformed(evt);
            }
        });

        btnReanudar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReanudar1.setText("Reanudar");
        btnReanudar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReanudar1ActionPerformed(evt);
            }
        });

        btnReanudar2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReanudar2.setText("Reanudar");
        btnReanudar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReanudar2ActionPerformed(evt);
            }
        });

        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFinalizar.setText("Finalizar Proceso");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        lblContador2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContador2.setText("0");
        lblContador2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblContador1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContador1.setText("0");
        lblContador1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSuspender1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addGap(139, 139, 139))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnReanudar1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSuspender2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnReanudar2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblContador1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblContador2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnComenzar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReanudar1)
                    .addComponent(btnReanudar2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuspender1)
                    .addComponent(btnSuspender2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContador2)
                    .addComponent(lblContador1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado1)
                    .addComponent(lblEstado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComenzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComenzarActionPerformed
        // TODO add your handling code here:
        if (!procesoIniciado) {
        h1 = new Hilo("Hilo1", lblContador1, lblEstado1);
        h2 = new Hilo("Hilo2", lblContador2, lblEstado2);
        
        h1.start();
        h2.start();
        
        btnComenzar.setEnabled(false);
        btnFinalizar.setEnabled(true);
        btnSuspender1.setEnabled(true);
        btnSuspender2.setEnabled(true);
        
        procesoIniciado = true;
        }
    }//GEN-LAST:event_btnComenzarActionPerformed

    private void btnSuspender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuspender2ActionPerformed
        // TODO add your handling code here:
         if (h2 != null) {
        h2.suspender();
        btnSuspender2.setEnabled(false);
        btnReanudar2.setEnabled(true);
    }
    }//GEN-LAST:event_btnSuspender2ActionPerformed

    private void btnReanudar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReanudar2ActionPerformed
        // TODO add your handling code here:
        if (h2 != null) {
        h2.reanudar();
        btnSuspender2.setEnabled(true);
        btnReanudar2.setEnabled(false);
    }
    }//GEN-LAST:event_btnReanudar2ActionPerformed

    private void btnReanudar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReanudar1ActionPerformed
        // TODO add your handling code here:
        if (h1 != null) {
            h1.reanudar();
            btnSuspender1.setEnabled(true);
            btnReanudar1.setEnabled(false);
        }
    }//GEN-LAST:event_btnReanudar1ActionPerformed

    private void btnSuspender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuspender1ActionPerformed
        // TODO add your handling code here:
        if (h1 != null) {
            h1.suspender();
            btnSuspender1.setEnabled(false);
            btnReanudar1.setEnabled(true);
        }
    }//GEN-LAST:event_btnSuspender1ActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
         if (h1 != null) h1.detener();
        if (h2 != null) h2.detener();
        
        // Restablecer interfaz
        btnComenzar.setEnabled(true);
        btnFinalizar.setEnabled(false);
        btnSuspender1.setEnabled(false);
        btnReanudar1.setEnabled(false);
        btnSuspender2.setEnabled(false);
        btnReanudar2.setEnabled(false);
        
        procesoIniciado = false;
    }//GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComenzar;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnReanudar1;
    private javax.swing.JButton btnReanudar2;
    private javax.swing.JButton btnSuspender1;
    private javax.swing.JButton btnSuspender2;
    private javax.swing.JLabel lblContador1;
    private javax.swing.JLabel lblContador2;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblEstado2;
    // End of variables declaration//GEN-END:variables
}
